#!/bin/sh

case "$SSH_ORIGINAL_COMMAND" in
	"git2docker")
		/opt/git2docker/git2docker
		;;
	git-*)
		/opt/git2docker/gitreceive $1 $2 $3
		;;
	backup:$option)
		echo backuping $option
		;;
	*)
		echo "Access Denied!!"
		;;
esac
